name: blade
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=24.2
  - pip:
      - datasets==2.21.0
      - huggingface-hub==0.24.7
      - numpy==2.1.0
      - sentencepiece==0.2.0
      - transformers==4.43.4
      - tokenizers==0.19.1
      - torch==2.7.1
      - torchaudio==2.7.1
      - torchvision==0.22.1
      - tqdm==4.66.5
      - accelerate==1.7.0
